"use strict";
exports.__esModule = true;
var notificationClient = require("./build/services/notification/v1/notification_pb");
exports.notificationClient = notificationClient;
var notificationServer = require("./build/services/notification/v1/notification_grpc_pb");
exports.notificationServer = notificationServer;
var budgetClient = require("./build/services/budget/v1/budget_pb");
exports.budgetClient = budgetClient;
var budgetServer = require("./build/services/budget/v1/budget_grpc_pb");
exports.budgetServer = budgetServer;
